### ISSUE TITLE
Typing in command line doesn't seem to work.

### ISSUE THREAD

**Issue by the-garbage-which-belongs-to-waffle** [daniel5151/ANESE#11]
Title. Tried in game, and pre-selection. May be my error, sorry if so.

**Comment by daniel5151** [comment]
Err, could you provide some more details? What exactly are you trying to accomplish?

**Comment by the-garbage-which-belongs-to-waffle** [comment]
I'm trying to enable the --wideNES flag.

**Comment by daniel5151** [comment]
Hmm, while I haven't touched the project in quite a while, I downloaded the latest release binary and passing `--widenes` via the CLI works just fine. Do bear in mind that it is case sensitive (i.e: `--wideNES` is not valid, but `--widenes` is).

**Comment by the-garbage-which-belongs-to-waffle** [comment]
Thank you!
