### ISSUE TITLE
Crash on absence of ALSA library

### ISSUE THREAD

**Issue by MrKOSMOS** [daniel5151/ANESE#14]
Hello,
Here from an arm64 edge case build, and it seems to compile 'fine' with some ~~errors~~ warnings, with the whole terminal build output attached below.
[erroranese (1).txt](https://github.com/daniel5151/ANESE/files/7643443/erroranese.1.txt)
Sadly, after attempting to run the emulator it seems to crash. My guess is the ALSA library, or lack thereof: my system doesn't even allow installing it.
By the way, is there any easy way to exclude the ALSA capabilities from the build? Would probably help with debugging. Also I kind of want to check out wideNes...
Thanks in advance

**Comment by daniel5151** [comment]
While I'd love to help, I haven't touched this codebase in _many_ years, and in those years, the very little knowledge of CMake and SDL that I acquired while working on ANESE have pretty much entirely evaporated...

I'd be more than happy to merge any fixes you come up with (presumably as a optional compilation flag?), but I'm afraid I won't be able to offer any help myself.

Best of luck.

**Comment by MrKOSMOS** [comment]
Ah well hehe. I will try then
Thanks

**Comment by MrKOSMOS** [comment]
Huh
After removing every reference to audio playback, it still doesn't work... But it doesn't crash. Not sure if it was crashing before anyway... But the emulator window just doesn't display anything, and neither does the wideNES one, both just look like a crashed program showing what's behind it.
Whelp, that's the quirk of edge cases... Time to check out the output from before.
I'll return here when I'm done with it

P.S. Also the file input system doesn't seem to support parentheses, might not support extended characters at all

**Comment by MrKOSMOS** [comment]
Ugh. It's not an app error, it's an Xlib error... Oh well, that's a report for somewhere else, since it seems to be related to the X virtual buffer and vnc sooooooo...
Marking it as solved
