### ISSUE TITLE
Any concerns about redistribution?

### ISSUE THREAD

**Issue by jonathanpeppers** [daniel5151/ANESE#16]
Hey, I wanted to let you know about a toolkit (prototype) I made for writing NES programs in C#:

https://github.com/jonathanpeppers/dotnes

I just wanted to bundle some simple NES emulator that runs on Windows & Mac, and yours fit the bill to redistribute for this.

I think I gave proper attribution, included your license, and everything, but let me know if there are any concerns or changes, you'd like me to make. Thank you so much for this project!

**Comment by daniel5151** [comment]
Oh, wow, that's a really nifty project! I actually also work for Microsoft and took part in Hackathon (though, unlike you, I don't have much in the way of a cool video or working project to show off, hah!)

And yep, I took a quick gander at how you bundled it - and it all looks good to me 😄 

I'll admit - I'm a little surprised you picked ANESE as your NES emulator, given how shoddy it is compared to other stuff out there... but hey, if it works, it works 😅
