### ISSUE TITLE
Failed to open directory

### ISSUE THREAD

**Issue by MobCat** [daniel5151/ANESE#6]
so the first time I ran ANESE it ran fine so I was OK I'll load some of my own roms into this and now this is all I get when I try and run ANESE now
https://i.imgur.com/o0VWG45.png
This is on windows 10 Enterprise version 1803
I deleted all of my roms expect for the 2048 rom it came with and still the same issue
I moved ANESE to the root of my C:\ and still same issue
I ran ANESE as administrator still same issue
I download and tried to run ANESE 0.9.0 still same issue
I have a feeling ANESE is trying to get cfg info or something from my docs but is using the old windows xp documents and settings prefix instead of the new win 7 Users folder or %username%
If I knew where ANESE was trying to save it's settings I probable could manually tell it to load from C:\Users but I don't know where / if ANESE saves cfg files

**Comment by daniel5151** [comment]
I use the cfgpath library for saving ANESE's config in different places depending on the OS. 
IIRC (just looking at cfgpath's code), the config should be at %appdata%\anese.ini

Tweak the config, and you should be able to get back up and running!
